import { execSync } from "child_process";
import * as fs from "fs";
import * as path from "path";

const CONTRACT_NAME = "MistCommute";

// Relative path to fhevm-hardhat-template
const rel = "../fhevm-hardhat-template";

// Output directory for ABI files
const outdir = path.resolve("./abi");

if (!fs.existsSync(outdir)) {
  fs.mkdirSync(outdir);
}

const dir = path.resolve(rel);
const dirname = path.basename(dir);

const line = "\n===================================================================\n";

if (!fs.existsSync(dir)) {
  console.error(
    `${line}Unable to locate ${rel}. Expecting ${dirname} at root level${line}`
  );
  process.exit(1);
}

const deploymentsDir = path.join(dir, "deployments");

function deployOnHardhatNode() {
  if (process.platform === "win32") {
    console.log("Auto-deployment not supported on Windows. Please deploy manually.");
    return;
  }
  try {
    console.log("Attempting to auto-deploy on Hardhat node...");
    execSync(`cd ${dir} && npx hardhat deploy --network localhost`, {
      stdio: "inherit",
    });
  } catch (e) {
    console.error(`${line}Auto-deployment failed: ${e}${line}`);
    process.exit(1);
  }
}

function readDeployment(chainName, chainId, contractName, optional) {
  const chainDeploymentDir = path.join(deploymentsDir, chainName);

  if (!fs.existsSync(chainDeploymentDir) && chainId === 31337) {
    // Try to auto-deploy the contract on hardhat node
    deployOnHardhatNode();
  }

  if (!fs.existsSync(chainDeploymentDir)) {
    console.error(
      `${line}Unable to locate '${chainDeploymentDir}' directory.\n\n1. Goto '${dirname}' directory\n2. Run 'npx hardhat deploy --network ${chainName}'.${line}`
    );
    if (!optional) {
      process.exit(1);
    }
    return undefined;
  }

  const contractPath = path.join(chainDeploymentDir, `${contractName}.json`);
  if (!fs.existsSync(contractPath)) {
    console.error(
      `${line}Contract ${contractName} not found in ${chainDeploymentDir}.\n\nPlease deploy the contract first.${line}`
    );
    if (!optional) {
      process.exit(1);
    }
    return undefined;
  }

  const jsonString = fs.readFileSync(contractPath, "utf-8");
  const obj = JSON.parse(jsonString);
  obj.chainId = chainId;

  return obj;
}

// Deploy on localhost (auto-deploy on Unix systems)
const deployLocalhost = readDeployment("localhost", 31337, CONTRACT_NAME, false);

// Sepolia is optional
let deploySepolia = readDeployment("sepolia", 11155111, CONTRACT_NAME, true);
if (!deploySepolia) {
  console.log("Sepolia deployment not found, using placeholder address.");
  deploySepolia = { 
    abi: deployLocalhost.abi, 
    address: "0x0000000000000000000000000000000000000000" 
  };
}

// Verify ABI consistency between networks
if (deployLocalhost && deploySepolia && deploySepolia.address !== "0x0000000000000000000000000000000000000000") {
  if (JSON.stringify(deployLocalhost.abi) !== JSON.stringify(deploySepolia.abi)) {
    console.error(
      `${line}Deployments on localhost and Sepolia have different ABIs. Consider re-deploying.${line}`
    );
    process.exit(1);
  }
}

// Generate TypeScript ABI file
const tsCode = `/*
  This file is auto-generated by 'npm run genabi'.
  Do not edit manually.
*/
export const ${CONTRACT_NAME}ABI = ${JSON.stringify({ abi: deployLocalhost.abi }, null, 2)} as const;
`;

// Generate TypeScript addresses file
const tsAddresses = `/*
  This file is auto-generated by 'npm run genabi'.
  Do not edit manually.
*/
export const ${CONTRACT_NAME}Addresses = { 
  "11155111": { 
    address: "${deploySepolia.address}", 
    chainId: 11155111, 
    chainName: "sepolia" 
  },
  "31337": { 
    address: "${deployLocalhost.address}", 
    chainId: 31337, 
    chainName: "localhost" 
  },
} as const;

export type ChainId = keyof typeof ${CONTRACT_NAME}Addresses;
`;

console.log(`✅ Generated ${path.join(outdir, `${CONTRACT_NAME}ABI.ts`)}`);
console.log(`✅ Generated ${path.join(outdir, `${CONTRACT_NAME}Addresses.ts`)}`);
console.log("\nContract Addresses:");
console.log(`  Localhost (31337): ${deployLocalhost.address}`);
console.log(`  Sepolia (11155111): ${deploySepolia.address}`);

fs.writeFileSync(path.join(outdir, `${CONTRACT_NAME}ABI.ts`), tsCode, "utf-8");
fs.writeFileSync(
  path.join(outdir, `${CONTRACT_NAME}Addresses.ts`),
  tsAddresses,
  "utf-8"
);

