"use client";

import { useEffect, useState, useCallback } from "react";
import { ethers } from "ethers";
import { useFhevm } from "@/fhevm/useFhevm";

// Will be generated by genabi script
let MistCommuteABI: any = null;
let MistCommuteAddresses: any = null;

// Dynamic import to avoid build errors before ABI generation
if (typeof window !== "undefined") {
  import("@/abi/MistCommuteABI").then((mod) => {
    MistCommuteABI = mod.MistCommuteABI;
  }).catch(() => {
    console.warn("MistCommuteABI not yet generated. Run 'npm run genabi'.");
  });

  import("@/abi/MistCommuteAddresses").then((mod) => {
    MistCommuteAddresses = mod.MistCommuteAddresses;
  }).catch(() => {
    console.warn("MistCommuteAddresses not yet generated. Run 'npm run genabi'.");
  });
}

/**
 * Hook to interact with MistCommute smart contract
 */
export function useMistCommuteContract(
  provider: ethers.BrowserProvider | null,
  account: string | undefined,
  chainId: number | undefined
) {
  const { instance: fhevmInstance } = useFhevm();
  const [contract, setContract] = useState<ethers.Contract | null>(null);
  const [contractAddress, setContractAddress] = useState<string | null>(null);

  // Initialize contract
  useEffect(() => {
    if (!provider || !chainId || !MistCommuteABI || !MistCommuteAddresses) {
      setContract(null);
      setContractAddress(null);
      return;
    }

    const initContract = async () => {
      try {
        const addressInfo = MistCommuteAddresses[String(chainId)];
        if (!addressInfo) {
          console.error(`MistCommute not deployed on chainId ${chainId}`);
          setContract(null);
          setContractAddress(null);
          return;
        }

        const contractAddr = addressInfo.address;
        
        // Check if contract address is zero (not deployed)
        if (!contractAddr || contractAddr === "0x0000000000000000000000000000000000000000") {
          console.error(`❌ MistCommute contract not deployed on chainId ${chainId}. Please deploy the contract first.`);
          setContract(null);
          setContractAddress(null);
          return;
        }
        
        // Verify contract exists by checking code size
        const code = await provider.getCode(contractAddr);
        if (code === "0x" || code === "0x0") {
          console.error(`❌ No contract found at address ${contractAddr} on chainId ${chainId}. Contract may not be deployed yet.`);
          setContract(null);
          setContractAddress(null);
          return;
        }
        
        console.log(`✅ Contract verified at ${contractAddr} (code size: ${code.length} bytes)`);

        // Get signer for sending transactions
        const signer = account ? await provider.getSigner(account) : provider;
        const contractInstance = new ethers.Contract(
          contractAddr,
          MistCommuteABI.abi,
          signer
        );

        // Test contract is accessible by calling a view function
        try {
          await contractInstance.totalCommutes();
          console.log(`✅ Contract is accessible and responding`);
        } catch (err) {
          console.warn(`⚠️ Contract may not be fully initialized:`, err);
        }

        setContract(contractInstance);
        setContractAddress(contractAddr);
        console.log(`✅ MistCommute contract loaded at ${contractAddr}`);
      } catch (error) {
        console.error("Failed to initialize contract:", error);
        setContract(null);
        setContractAddress(null);
      }
    };

    initContract();
  }, [provider, account, chainId]);

  /**
   * Submit encrypted commute data
   */
  const submitCommute = useCallback(
    async (
      departureMinutes: number,
      arrivalMinutes: number,
      routeName: string,
      commuteType: number
    ): Promise<{ success: boolean; commuteId?: number; error?: string }> => {
      if (!contract || !fhevmInstance || !account || !contractAddress) {
        let errorMsg = "Contract or FHEVM not ready";
        if (!contractAddress) {
          errorMsg = `MistCommute contract not deployed on this network. Please deploy the contract first or switch to a network where it's deployed.`;
        }
        return { success: false, error: errorMsg };
      }
      
      // Additional check: ensure contract address is not zero
      if (contractAddress === "0x0000000000000000000000000000000000000000") {
        return { 
          success: false, 
          error: "MistCommute contract not deployed on this network. Please deploy the contract first or run 'npm run genabi' after deployment." 
        };
      }

      try {
        const duration = arrivalMinutes - departureMinutes;

        console.log("🔐 Creating encrypted input...", {
          contractAddress,
          account,
          departureMinutes,
          arrivalMinutes,
          duration,
        });
        
        // Validate addresses before creating encrypted input
        if (!contractAddress || contractAddress === "0x0000000000000000000000000000000000000000") {
          return { 
            success: false, 
            error: "Invalid contract address. Please ensure the contract is deployed." 
          };
        }
        
        if (!account) {
          return { 
            success: false, 
            error: "Invalid user address. Please connect your wallet." 
          };
        }

        // Create encrypted input
        console.log("🔐 Calling createEncryptedInput with:", { contractAddress, account });
        const input = fhevmInstance.createEncryptedInput(contractAddress, account);
        input.add32(departureMinutes);
        input.add32(arrivalMinutes);
        input.add32(duration);

        console.log("🔐 Encrypting input...");
        let encryptedData;
        try {
          encryptedData = await input.encrypt();
          console.log("✅ Encryption successful", {
            handleCount: encryptedData.handles.length,
            inputProofLength: encryptedData.inputProof.length,
            handles: encryptedData.handles.slice(0, 3), // Only log first 3 handles
          });
        } catch (encryptError: any) {
          console.error("❌ Encryption failed:", encryptError);
          return { 
            success: false, 
            error: `Encryption failed: ${encryptError.message || "Unknown error"}. Please ensure Hardhat node is running with FHEVM plugin.` 
          };
        }

        // Validate encrypted data
        if (!encryptedData || !encryptedData.handles || encryptedData.handles.length < 3) {
          return { 
            success: false, 
            error: "Invalid encrypted data: expected 3 handles but got " + (encryptedData?.handles?.length || 0) 
          };
        }

        if (!encryptedData.inputProof || encryptedData.inputProof.length === 0) {
          return { 
            success: false, 
            error: "Invalid encrypted data: input proof is missing or empty" 
          };
        }

        // Submit transaction
        console.log("📤 Submitting transaction...", {
          routeName,
          commuteType,
          handle0: encryptedData.handles[0],
          handle1: encryptedData.handles[1],
          handle2: encryptedData.handles[2],
        });
        
        let tx;
        try {
          tx = await contract.submitCommute(
            encryptedData.handles[0],
            encryptedData.handles[1],
            encryptedData.handles[2],
            encryptedData.inputProof,
            routeName,
            commuteType
          );
        } catch (txError: any) {
          console.error("❌ Transaction submission failed:", txError);
          
          // Try to provide more helpful error messages
          if (txError.message?.includes("execution reverted")) {
            if (txError.data === "0x7a47c9a2" || txError.message.includes("0x7a47c9a2")) {
              return {
                success: false,
                error: "Input verification failed. This usually means the encrypted input proof is invalid. Please ensure:\n1. Hardhat node is running with FHEVM plugin\n2. Contract is correctly deployed\n3. FHEVM metadata is properly loaded"
              };
            }
            return {
              success: false,
              error: `Transaction reverted: ${txError.reason || txError.message || "Unknown error"}. Error data: ${txError.data || "none"}`
            };
          }
          throw txError;
        }

        console.log("⏳ Waiting for transaction receipt...", tx.hash);
        const receipt = await tx.wait();

        // Parse event to get commute ID
        const event = receipt.logs.find((log: any) => {
          try {
            const parsed = contract.interface.parseLog(log);
            return parsed?.name === "CommuteSubmitted";
          } catch {
            return false;
          }
        });

        let commuteId = 0;
        if (event) {
          const parsed = contract.interface.parseLog(event);
          commuteId = Number(parsed?.args?.commuteId || 0);
        }

        return { success: true, commuteId };
      } catch (error: any) {
        console.error("Failed to submit commute:", error);
        return { success: false, error: error.message || "Transaction failed" };
      }
    },
    [contract, fhevmInstance, account, contractAddress]
  );

  /**
   * Get user's commute IDs
   */
  const getUserCommuteIds = useCallback(
    async (userAddress?: string): Promise<number[]> => {
      if (!contract) return [];

      try {
        const address = userAddress || account;
        if (!address) return [];

        const ids = await contract.getUserCommuteIds(address);
        return ids.map((id: bigint) => Number(id));
      } catch (error) {
        console.error("Failed to get commute IDs:", error);
        return [];
      }
    },
    [contract, account]
  );

  /**
   * Get community statistics
   */
  const getCommunityStats = useCallback(async (): Promise<{
    totalCommutes: number;
    morningCongested: boolean;
    eveningCongested: boolean;
  } | null> => {
    if (!contract) return null;

    try {
      const stats = await contract.getCommunityStats();
      return {
        totalCommutes: Number(stats[0]),
        morningCongested: stats[1],
        eveningCongested: stats[2],
      };
    } catch (error) {
      console.error("Failed to get community stats:", error);
      return null;
    }
  }, [contract]);

  /**
   * Get congestion level for a time slot
   */
  const getCongestionLevel = useCallback(
    async (slot: number): Promise<number | null> => {
      if (!contract) return null;

      try {
        const level = await contract.getCongestionLevel(slot);
        return Number(level);
      } catch (error) {
        console.error("Failed to get congestion level:", error);
        return null;
      }
    },
    [contract]
  );

  return {
    contract,
    contractAddress,
    submitCommute,
    getUserCommuteIds,
    getCommunityStats,
    getCongestionLevel,
  };
}

