/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface MistCommuteInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "confidentialProtocolId"
      | "eveningCount"
      | "getCommunityStats"
      | "getCongestionLevel"
      | "getEncryptedStats"
      | "getUserCommuteDetails"
      | "getUserCommuteIds"
      | "grantStatsAccess"
      | "morningCount"
      | "owner"
      | "submitCommute"
      | "totalCommutes"
      | "updateThresholds"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CommuteSubmitted"
      | "CongestionUpdated"
      | "StatsAccessGranted"
      | "ThresholdsUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "eveningCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCommunityStats",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCongestionLevel",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedStats",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUserCommuteDetails",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserCommuteIds",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantStatsAccess",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "morningCount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "submitCommute",
    values: [BytesLike, BytesLike, BytesLike, BytesLike, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalCommutes",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateThresholds",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "eveningCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCommunityStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCongestionLevel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserCommuteDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserCommuteIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "grantStatsAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "morningCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitCommute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalCommutes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateThresholds",
    data: BytesLike
  ): Result;
}

export namespace CommuteSubmittedEvent {
  export type InputTuple = [
    user: AddressLike,
    commuteId: BigNumberish,
    commuteType: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    commuteId: bigint,
    commuteType: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    user: string;
    commuteId: bigint;
    commuteType: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CongestionUpdatedEvent {
  export type InputTuple = [
    slot: BigNumberish,
    level: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [slot: bigint, level: bigint, timestamp: bigint];
  export interface OutputObject {
    slot: bigint;
    level: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StatsAccessGrantedEvent {
  export type InputTuple = [recipient: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [recipient: string, timestamp: bigint];
  export interface OutputObject {
    recipient: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ThresholdsUpdatedEvent {
  export type InputTuple = [timestamp: BigNumberish];
  export type OutputTuple = [timestamp: bigint];
  export interface OutputObject {
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MistCommute extends BaseContract {
  connect(runner?: ContractRunner | null): MistCommute;
  waitForDeployment(): Promise<this>;

  interface: MistCommuteInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  eveningCount: TypedContractMethod<[], [bigint], "view">;

  getCommunityStats: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        _totalCommutes: bigint;
        _morningCount: bigint;
        _eveningCount: bigint;
      }
    ],
    "view"
  >;

  getCongestionLevel: TypedContractMethod<
    [slot: BigNumberish],
    [bigint],
    "view"
  >;

  getEncryptedStats: TypedContractMethod<
    [],
    [
      [string, string, string, bigint, bigint] & {
        _totalDurationSum: string;
        _morningDurationSum: string;
        _eveningDurationSum: string;
        _morningCount: bigint;
        _eveningCount: bigint;
      }
    ],
    "view"
  >;

  getUserCommuteDetails: TypedContractMethod<
    [commuteId: BigNumberish],
    [
      [string, string, string, string, bigint, bigint] & {
        departure: string;
        arrival: string;
        duration: string;
        routeName: string;
        commuteType: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  getUserCommuteIds: TypedContractMethod<
    [user: AddressLike],
    [bigint[]],
    "view"
  >;

  grantStatsAccess: TypedContractMethod<
    [recipient: AddressLike],
    [void],
    "nonpayable"
  >;

  morningCount: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  submitCommute: TypedContractMethod<
    [
      encryptedDeparture: BytesLike,
      encryptedArrival: BytesLike,
      encryptedDuration: BytesLike,
      inputProof: BytesLike,
      routeName: string,
      commuteType: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  totalCommutes: TypedContractMethod<[], [bigint], "view">;

  updateThresholds: TypedContractMethod<
    [
      newLowThreshold: BytesLike,
      newHighThreshold: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "eveningCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getCommunityStats"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        _totalCommutes: bigint;
        _morningCount: bigint;
        _eveningCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCongestionLevel"
  ): TypedContractMethod<[slot: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getEncryptedStats"
  ): TypedContractMethod<
    [],
    [
      [string, string, string, bigint, bigint] & {
        _totalDurationSum: string;
        _morningDurationSum: string;
        _eveningDurationSum: string;
        _morningCount: bigint;
        _eveningCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserCommuteDetails"
  ): TypedContractMethod<
    [commuteId: BigNumberish],
    [
      [string, string, string, string, bigint, bigint] & {
        departure: string;
        arrival: string;
        duration: string;
        routeName: string;
        commuteType: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserCommuteIds"
  ): TypedContractMethod<[user: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "grantStatsAccess"
  ): TypedContractMethod<[recipient: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "morningCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "submitCommute"
  ): TypedContractMethod<
    [
      encryptedDeparture: BytesLike,
      encryptedArrival: BytesLike,
      encryptedDuration: BytesLike,
      inputProof: BytesLike,
      routeName: string,
      commuteType: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "totalCommutes"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "updateThresholds"
  ): TypedContractMethod<
    [
      newLowThreshold: BytesLike,
      newHighThreshold: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "CommuteSubmitted"
  ): TypedContractEvent<
    CommuteSubmittedEvent.InputTuple,
    CommuteSubmittedEvent.OutputTuple,
    CommuteSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "CongestionUpdated"
  ): TypedContractEvent<
    CongestionUpdatedEvent.InputTuple,
    CongestionUpdatedEvent.OutputTuple,
    CongestionUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "StatsAccessGranted"
  ): TypedContractEvent<
    StatsAccessGrantedEvent.InputTuple,
    StatsAccessGrantedEvent.OutputTuple,
    StatsAccessGrantedEvent.OutputObject
  >;
  getEvent(
    key: "ThresholdsUpdated"
  ): TypedContractEvent<
    ThresholdsUpdatedEvent.InputTuple,
    ThresholdsUpdatedEvent.OutputTuple,
    ThresholdsUpdatedEvent.OutputObject
  >;

  filters: {
    "CommuteSubmitted(address,uint256,uint8,uint256)": TypedContractEvent<
      CommuteSubmittedEvent.InputTuple,
      CommuteSubmittedEvent.OutputTuple,
      CommuteSubmittedEvent.OutputObject
    >;
    CommuteSubmitted: TypedContractEvent<
      CommuteSubmittedEvent.InputTuple,
      CommuteSubmittedEvent.OutputTuple,
      CommuteSubmittedEvent.OutputObject
    >;

    "CongestionUpdated(uint8,uint8,uint256)": TypedContractEvent<
      CongestionUpdatedEvent.InputTuple,
      CongestionUpdatedEvent.OutputTuple,
      CongestionUpdatedEvent.OutputObject
    >;
    CongestionUpdated: TypedContractEvent<
      CongestionUpdatedEvent.InputTuple,
      CongestionUpdatedEvent.OutputTuple,
      CongestionUpdatedEvent.OutputObject
    >;

    "StatsAccessGranted(address,uint256)": TypedContractEvent<
      StatsAccessGrantedEvent.InputTuple,
      StatsAccessGrantedEvent.OutputTuple,
      StatsAccessGrantedEvent.OutputObject
    >;
    StatsAccessGranted: TypedContractEvent<
      StatsAccessGrantedEvent.InputTuple,
      StatsAccessGrantedEvent.OutputTuple,
      StatsAccessGrantedEvent.OutputObject
    >;

    "ThresholdsUpdated(uint256)": TypedContractEvent<
      ThresholdsUpdatedEvent.InputTuple,
      ThresholdsUpdatedEvent.OutputTuple,
      ThresholdsUpdatedEvent.OutputObject
    >;
    ThresholdsUpdated: TypedContractEvent<
      ThresholdsUpdatedEvent.InputTuple,
      ThresholdsUpdatedEvent.OutputTuple,
      ThresholdsUpdatedEvent.OutputObject
    >;
  };
}
