/*
  This file is auto-generated by 'npm run genabi'.
  Do not edit manually.
  
  Contract ABI for MistCommute smart contract.
  Used for contract interaction in the frontend.
*/
export const MistCommuteABI = {
  "abi": [
    {
      "inputs": [],
      "stateMutability": "nonpayable",
      "type": "constructor"
    },
    {
      "inputs": [],
      "name": "ZamaProtocolUnsupported",
      "type": "error"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "internalType": "address",
          "name": "user",
          "type": "address"
        },
        {
          "indexed": true,
          "internalType": "uint256",
          "name": "commuteId",
          "type": "uint256"
        },
        {
          "indexed": false,
          "internalType": "enum MistCommute.CommuteType",
          "name": "commuteType",
          "type": "uint8"
        },
        {
          "indexed": false,
          "internalType": "uint256",
          "name": "timestamp",
          "type": "uint256"
        }
      ],
      "name": "CommuteSubmitted",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": false,
          "internalType": "enum MistCommute.TimeSlot",
          "name": "slot",
          "type": "uint8"
        },
        {
          "indexed": false,
          "internalType": "enum MistCommute.CongestionLevel",
          "name": "level",
          "type": "uint8"
        },
        {
          "indexed": false,
          "internalType": "uint256",
          "name": "timestamp",
          "type": "uint256"
        }
      ],
      "name": "CongestionUpdated",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "internalType": "address",
          "name": "recipient",
          "type": "address"
        },
        {
          "indexed": false,
          "internalType": "uint256",
          "name": "timestamp",
          "type": "uint256"
        }
      ],
      "name": "StatsAccessGranted",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": false,
          "internalType": "uint256",
          "name": "timestamp",
          "type": "uint256"
        }
      ],
      "name": "ThresholdsUpdated",
      "type": "event"
    },
    {
      "inputs": [],
      "name": "confidentialProtocolId",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "eveningCount",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "getCommunityStats",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "_totalCommutes",
          "type": "uint256"
        },
        {
          "internalType": "uint256",
          "name": "_morningCount",
          "type": "uint256"
        },
        {
          "internalType": "uint256",
          "name": "_eveningCount",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "enum MistCommute.TimeSlot",
          "name": "slot",
          "type": "uint8"
        }
      ],
      "name": "getCongestionLevel",
      "outputs": [
        {
          "internalType": "enum MistCommute.CongestionLevel",
          "name": "",
          "type": "uint8"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "getEncryptedStats",
      "outputs": [
        {
          "internalType": "euint32",
          "name": "_totalDurationSum",
          "type": "bytes32"
        },
        {
          "internalType": "euint32",
          "name": "_morningDurationSum",
          "type": "bytes32"
        },
        {
          "internalType": "euint32",
          "name": "_eveningDurationSum",
          "type": "bytes32"
        },
        {
          "internalType": "uint256",
          "name": "_morningCount",
          "type": "uint256"
        },
        {
          "internalType": "uint256",
          "name": "_eveningCount",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "uint256",
          "name": "commuteId",
          "type": "uint256"
        }
      ],
      "name": "getUserCommuteDetails",
      "outputs": [
        {
          "internalType": "euint32",
          "name": "departure",
          "type": "bytes32"
        },
        {
          "internalType": "euint32",
          "name": "arrival",
          "type": "bytes32"
        },
        {
          "internalType": "euint32",
          "name": "duration",
          "type": "bytes32"
        },
        {
          "internalType": "string",
          "name": "routeName",
          "type": "string"
        },
        {
          "internalType": "enum MistCommute.CommuteType",
          "name": "commuteType",
          "type": "uint8"
        },
        {
          "internalType": "uint256",
          "name": "timestamp",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "user",
          "type": "address"
        }
      ],
      "name": "getUserCommuteIds",
      "outputs": [
        {
          "internalType": "uint256[]",
          "name": "",
          "type": "uint256[]"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "recipient",
          "type": "address"
        }
      ],
      "name": "grantStatsAccess",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "morningCount",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "owner",
      "outputs": [
        {
          "internalType": "address",
          "name": "",
          "type": "address"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "externalEuint32",
          "name": "encryptedDeparture",
          "type": "bytes32"
        },
        {
          "internalType": "externalEuint32",
          "name": "encryptedArrival",
          "type": "bytes32"
        },
        {
          "internalType": "externalEuint32",
          "name": "encryptedDuration",
          "type": "bytes32"
        },
        {
          "internalType": "bytes",
          "name": "inputProof",
          "type": "bytes"
        },
        {
          "internalType": "string",
          "name": "routeName",
          "type": "string"
        },
        {
          "internalType": "enum MistCommute.CommuteType",
          "name": "commuteType",
          "type": "uint8"
        }
      ],
      "name": "submitCommute",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "commuteId",
          "type": "uint256"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "totalCommutes",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "externalEuint32",
          "name": "newLowThreshold",
          "type": "bytes32"
        },
        {
          "internalType": "externalEuint32",
          "name": "newHighThreshold",
          "type": "bytes32"
        },
        {
          "internalType": "bytes",
          "name": "inputProof",
          "type": "bytes"
        }
      ],
      "name": "updateThresholds",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    }
  ]
} as const;
