/*
  This file is auto-generated by 'npm run genabi'.
  Do not edit manually.
*/
export const MistCommuteAddresses = { 
  "11155111": { 
    address: "0x78Fc00AE2477e3f0eb6d337aB2F43BE6F6Aa1B9B", 
    chainId: 11155111, 
    chainName: "sepolia" 
  },
  "31337": { 
    address: "0x78Fc00AE2477e3f0eb6d337aB2F43BE6F6Aa1B9B", 
    chainId: 31337, 
    chainName: "localhost" 
  },
} as const;

export type ChainId = keyof typeof MistCommuteAddresses;
